apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-20003
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.repo }}
    path: test-20003-deploy/src/main/resources/apps/spark-infrastructure
    targetRevision: {{ .Values.spec.targetRevision }}
    {{ if .Values.spec.helm.valueFiles }}
    helm:
      valueFiles:
        {{- range .Values.spec.helm.valueFiles }}
        - {{ . }}
        {{- end }}    
    {{ end }}
  {{- with .Values.spec.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}